language: rust
sudo: false

cache: cargo

os: 
  - linux

rust:
  - 1.22.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: stable
      env: BUILD_FMT=1

before_script: 
 - if [ -n "$BUILD_FMT" ]; then rustup component add rustfmt-preview; fi

script:
- |
   if [ -n "$BUILD_FMT" ]; then
     cargo fmt -- --check
   else
     cargo update
     cargo update -p stb_truetype --precise 0.2.2
     cargo update -p rusttype --precise 0.7.1
     cargo update -p lazy_static --precise 1.1.0
     cargo check
   fi
